### ISSUE TITLE
Timestamp de la ligne 2 mal initialisé

### ISSUE THREAD

**Issue by Dreaky255** [maximelebreton/alertes-leboncoin#10]
Actuellement (version 33), lorsque deux annonces sont créées dans la feuille (deux lignes), le timestamp de la ligne 2 est systématiquement actualisé à 0 (01/01/1970 01:00:00). Ce qui fait qu'à chaque update, un mail est envoyé avec la totalité des annonces correspondant à l'URL insérée.

Testé avec une feuille vierge (copie vierge), ou bien plusieurs URL, sur plusieurs types d'annonces, reproductible à chaque fois.

**Comment by maximelebreton** [comment]
Je viens de tester sur plusieurs feuilles de calcul et je n'ai pas ce problème,
pourriez vous me donner plus de détails, ou me faire une copie d'écran de la partie feuille de calcul et la partie éditeur de scripts ?

**Comment by maximelebreton** [comment]
Sans nouvelles, je ferme l'issue.
