### ISSUE TITLE
Ne pas envoyer de mail s'il y a 0 résultat

### ISSUE THREAD

**Issue by bisonfute** [maximelebreton/alertes-leboncoin#11]
Bonjour,
Lié à #8, si une alerte très fréquente donne 0 résultat, je trouve pertinent de ne pas envoyer de mail. Pour l'instant, je reçois un email qui me dit que la recherche a donné 0 résultat.

**Comment by maximelebreton** [comment]
effectivement, je viens de patcher avec la `5.1.7`, cela devrait résoudre le problème.

**Comment by maximelebreton** [comment]
@bisonfute cela a t'il résolu votre problème ?

**Comment by bisonfute** [comment]
@maximelebreton oui, je ne reçois plus les mails avec 0 résultats.
Par contre, je ne sais pas si c'est lié à ça ou à #8 mais je ne reçois plus les emails dont j'ai configuré une hourFrequency.
J'ai configuré 3 annonces : une sans paramètre avancé, et les 2 autres : {"hourFrequency":24}, {"hourFrequency":48}.

J'ai mis le déclencheur sur 2 heures.

Je reçois bien les alertes pour l'annonce sans paramètres avances mais je ne reçois plus les alertes pour les autres.

Est-ce que je peux faire qqch pour debug?

**Comment by maximelebreton** [comment]
effectivement, il y'avait un problème dû à la nouvelle fonctionnalité #8 que je viens de résoudre en 5.1.8.
Maintenant tout devrait rentrer dans l'ordre, mais j'attends votre confirmation.

**Comment by maximelebreton** [comment]
pouvez vous m'indiquer si cela a résolu votre problème @bisonfute ?

**Comment by bisonfute** [comment]
bonjour @maximelebreton et désolé du très long temps de réponse!
je te confirme que ça marche très bien!
j'avais un doute, mais c'était à cause du #15 qui me bloquait une ligne.

merci bcp!
