### ISSUE TITLE
Fourchette de prix

### ISSUE THREAD

**Issue by lesmickeys** [maximelebreton/alertes-leboncoin#12]
Bonjour,
Est-il possible d'ajouter deux colonnes permettant d'indiquer un prix mini et maxi afin de filtrer les annonces sélectionnées idem à la version 3.12  de st3ph.
Merci pour votre réponse et merci pour votre travail.

**Comment by maximelebreton** [comment]
Bonjour @lesmickeys,
j'avoue que je ne comprends pas bien le but de cet ajout puisqu'il est possible de le faire directement via l'url générée par leboncoin lorsque les paramètres de recherche sont précisés :  

![image](https://cloud.githubusercontent.com/assets/1072425/21314248/46e63d96-c5f6-11e6-9452-15b7d5f7c644.png)

De plus, je suis assez réticent à cette idée pour deux raisons : 
- La première est que cela viendrait nuire à la [simplicité](https://github.com/maximelebreton/alertes-leboncoin/issues/2#issue-160232943) de l'ensemble (5 colonnes au lieu de 3)
- La deuxième est que toutes les catégories n'ont pas un prix min ou max (comme les offres d'emploi par exemple), donc l'usage me semble trop spécifique pour en faire des colonnes dédiées

Par contre, je suis curieux de comprendre votre usage, et s'il n'est pas trop spécifique, il serait possible de pouvoir spécifier le prix mini et maxi dans les [paramètres individuels avancés](https://github.com/maximelebreton/alertes-leboncoin#paramètres-individuels).
Les tranches de prix seraient d'ailleurs totalement personnalisables.
exemple (non implémenté) : ```{"minprice": 450, "maxprice": 985}```

**Comment by lesmickeys** [comment]
Bonjour et merci pour vos réponses mais l'intérêt de pouvoir sélectionner une plage de prix mini et maxi permet de ne pas être alerté trop souvent car certaines catégories types collection ou jeux/jouet ont un prix de selection maxi de 250€. Or certaines de mes recherches  se situent entre 500€ et 800€. Je reçois donc avec la sélection lbc toutes les alertes au delà de 250€.
Si vous  pensez que  cette modification alourdi le système de base, je suis preneur pour obtenir la démarche à suivre dans les paramètres avancés car cela me serait bien utile. Mais n'étant pas un as informatique difficile même impossible de le faire sans votre aide.

Cordialement. 
Et encore merci pour ce travail.

Le 19 déc. 2016 14:43, à 14:43, Maxime Le Breton <notifications@github.com> a écrit:

**Comment by maximelebreton** [comment]
effectivement, je comprends mieux le besoin, j'intégrerais les paramètres `minprice` et `maxprice` dans la prochaine version.

**Comment by lesmickeys** [comment]
Merci pour ces futurs modifications. 
Bonne soirée.

**Comment by maximelebreton** [comment]
C'est maintenant en place dans la `5.2.0`, via les paramètres individuels (`minprice` et `maxprice`) : https://github.com/maximelebreton/alertes-leboncoin#paramètres-individuels

**Comment by lesmickeys** [comment]
Merci pour cette nouvelle version. 
Bonne journée.

**Comment by lesmickeys** [comment]
Bonsoir, 
Pour utiliser la fonction minprice et maxprice, que faut-il indiquer dans la colonne "paramètres avancés"
J'ai essayé d'inscrire:{"minprice":200,"maxprice":900} mais ça ne fonctionne pas. 
Que veut dire "en passant par un objet JSON stringifié.
Merci d'avance.

**Comment by maximelebreton** [comment]
Le nom des paramètres que vous avez indiqué n'est pas correct (il s'agit de `minPrice` et non `minprice`, et `maxPrice` au lieu de `maxprice`), mais je vous ai induit en erreur dans mon exemple plus haut (je viens de corriger).
Par contre la documentation est bonne.

**Comment by lesmickeys** [comment]
Super content, ça fonctionne. 
Une nouvelle fois merci.
