### ISSUE TITLE
Petite coquille dans le code

### ISSUE THREAD

**Issue by tilowil** [maximelebreton/alertes-leboncoin#13]
Bonjour,
En passant à la version 5.2.1 puis 5.2.2, j'ai eu une erreur qui se produit sur un lancement manuel. En automatique, par le déclencheur, rien n'arrive. 
![screen shot 01-01-17 at 04 22 am](https://cloud.githubusercontent.com/assets/20038641/21580097/00abca56-cfda-11e6-8c5a-7e1ec4bbd40c.PNG)

J'ai donc cherché et je me suis rendu compte que dans le fichier dataSend.js vous appelez en ligne 151 la fonction getMailTextTemplate(), or il semblerait que cette fonction n'existe pas. Par contre il existe une fonction getTextMailTemplate() dans le fichier mail.js . Je n'ose pas faire la correction ne sachant pas lequel est le bon. 
En tout cas bravo pour ces versions qui ont grandement amélioré la version originale. 
Merci de votre aide pour corriger cette coquille.

**Comment by maximelebreton** [comment]
Effectivement, lors du refactoring celui ci m'a échappé !
C'est corrigé dans la 5.2.3
Merci pour le retour
