### ISSUE TITLE
coquille 2

### ISSUE THREAD

**Issue by tilowil** [maximelebreton/alertes-leboncoin#14]
Bonjour,
Merci pour la correction, mais une autre est apparue, toujours au lancement manuel
![screen shot 01-01-17 at 04 18 pm](https://cloud.githubusercontent.com/assets/20038641/21581746/e5f3666e-d03e-11e6-95fc-b3c66e9d81fd.PNG)

le mail part bien, mais le datetime de la colonne dernière annonce ne se s’écrit pas. et je n'ai que 13 annonces alors qu'avec 1 jour d'arret je devrai en avoir au moins 35. 
Ma configuration est la plus simple possible.
Paramètres	Valeurs
email	adresse1, adresse2 
showMap	FALSE
mapZoom	7
groupedResults	TRUE
showMailEditLink	FALSE

J'ai essayé de trouver ou est généré l'erreur mais je n'ai pas trouvé.
[Edit]
il semblerai que seule la première ligne de recherche soit prise en compte.
Titre	Lien	Dernière annonce
DDR	http://www.leboncoin.fr/annonces/offres/ile_de_france/occasions/?f=a&th=1&q=konami+borne	
Flipper 27	https://www.leboncoin.fr/annonces/offres/haute_normandie/?th=1&q=flipper%20-dauphin%20-foot	
Flipper 60	https://www.leboncoin.fr/annonces/offres/picardie/?th=1&q=flipper%20-dauphin%20-foot	
Flipper Collection	https://www.leboncoin.fr/collection/offres/ile_de_france/occasions/?th=1&q=flipper%20-dauphin%20-foot	
Flipper Hobbies	https://www.leboncoin.fr/sports_hobbies/offres/ile_de_france/occasions/?th=1&q=flipper%20-dauphin%20-foot	
pic-asso	https://www.leboncoin.fr/annonces/offres/ile_de_france/occasions/?th=1&q=pic-asso&parrot=0	
[/Edit]
Merci

**Comment by maximelebreton** [comment]
Bonjour, je viens de reproduire vos paramètres à partir d'une feuille vierge en 5.2.3 et je n'ai pas le problème.
Pouvez vous essayer de faire la même chose ?
Pour repartir sur une feuille vierge :  https://goo.gl/Awjw5f

**Comment by maximelebreton** [comment]
Pour info, lorsque vous avez une erreur, allez dans `outils > editeur de script > affichage > scripts d'execution`, et regardez la dernière ligne affichée (normalement il est indiqué le fichier et la ligne du problème). 
Cela permets d'avoir plus de détails ;)

**Comment by tilowil** [comment]
Merci de votre réponse si rapide.
- Je suis reparti d'une copie de la feuille de base (avec la caravanne) => OK
- J'ai ajouté mes 6 alertes d'un coup, l'erreur est réapparue => NOK
- J'ai ajouté les alertes une à une en lancant manuellement entre chaque ajout => OK
- J'ai remis la date de la dernière annonce à vide sur les 2 dernières lignes puis lancer manuellement  => OK
- idem sur les 3 dernières lignes => OK
- idem sur les 4 dernières lignes, l'erreur est revenue =>NOK
![screen shot 01-01-17 at 07 25 pm](https://cloud.githubusercontent.com/assets/20038641/21582452/4c0249c0-d058-11e6-8458-fc4073674bb3.PNG)

coté mails reçus, je pense que quand le mail contient au moins 140 annonces le message apparaît. Peut être une limitation de ce qui fait partir des mails.
![screen shot 01-01-17 at 07 26 pm](https://cloud.githubusercontent.com/assets/20038641/21582473/0de5d8cc-d059-11e6-9306-202ac634fc17.PNG)

**Comment by maximelebreton** [comment]
Pas facile à détecter celui là !
Encore un bug dû au refactoring, le processus de renvoi de mail individuels, lorsqu'un email groupé est trop lourd ne fonctionnait plus...
Passez en `5.2.4` et cela devrait résoudre le problème.
Merci pour le retour détaillé.

**Comment by tilowil** [comment]
De rien, Merci pour les corrections un 1 janvier ^_^. 
Je viens de faire la mise à jour pour moi tout est bon.
Encore merci et une très bonne Année 2017 pleine de bonnes alertes.
