### ISSUE TITLE
probleme gestion date passage nouvelle année

### ISSUE THREAD

**Issue by lefloz** [maximelebreton/alertes-leboncoin#15]
Salut Maxime,

petit problème suite a la nouvelle année.
Je pense que ça vient du fait que les années ne sont pas gérées, du coup la date de dernière annonce reste bloqué au 30/12 23h59.
Demain ça bloquera au 31/12 23h59 puisque ça ne sera plus "hier" ... et il n'y aura plus de notification jusqu'à ce qu'il n'y ait que des annonces de 2017 en 1ere page (disparition du 31/12 23h59).

L'ordonnancement actuel se fait de cette façon : 
30/12
29/12
28/12
...
aujourd'hui (01/01)
hier (01/01 moins 1 jour)

Tout rentrera dans l'ordre quand il n'y aura sur la 1ere page plus que des annonces de 2017 ... mais le bug se reproduira en 2018.

Bien à toi.
Florent (je t'avais contacté il y a qq temps pour comprendre le fonctionnement des librairies. Je te remercie et suis arrivé à mes fins sans difficultés grâce à tes explications et "liens")

**Comment by lefloz** [comment]
je suis allé trop vite .... les années sont bien gérées, le problème est que les annonces de 2016 sont "redatées" en 2017. Le 30/12/**2016** est devenu 30/12/**2017**
![capture](https://cloud.githubusercontent.com/assets/24865879/21582779/567f60aa-d066-11e6-94cd-b1bb0b1f4477.JPG)

**Comment by maximelebreton** [comment]
je suis sur le coup, j'ai détecté d'ou ça vient, je suis en train de corriger, merci florent !

**Comment by lefloz** [comment]
Toujours super réactif !!!
Bon "debug" et meilleurs voeux. Bye

2017-01-01 21:10 GMT+01:00 Maxime Le Breton <notifications@github.com>:

**Comment by maximelebreton** [comment]
A savoir, si une date censée être de 2016 a été mémorisée en 2017 (exemple 31/12/2017) dans la colonne, vous n'allez pas recevoir les mails avant l'année prochaine, donc n'oubliez pas de corriger la date (en cliquant simplement dessus, un datepicker doit s'ouvrir) !

**Comment by lefloz** [comment]
Fonctionne parfaitement en 5.2.4. Merci !
