### ISSUE TITLE
Affichage SMS "undefined"

### ISSUE THREAD

**Issue by ObiwanKennedyHep** [maximelebreton/alertes-leboncoin#17]
Bonjour,

Quand je reçois le texto sur mon mobile, je n'ai pas l'image et pas d'habillage du texte. En gros j'ai le titre de l'annonce puis systématiquement "undefined" puis le prix (sans texte devant indiquant que c'est le prix; puis l'URL).
Ce serait pas mal d'habiller un peu plus le SMS, d'y ajouter l'image et de supprimer ce "undefined".

Autre remarque : Lors de l'envoi d'un SMS, la notification en bas à droite indique 'Mail envoyé à xxxx" mais ne précise pas si un texto est également envoyé.

Merci encore pour ton super travail ! 

Je précise que tous mes tests ont été réalisés avec la dernière version 5.2.4.

**Comment by maximelebreton** [comment]
Bonjour @ObiwanKennedyHep, le problème de `undefined` doit être résolu en `5.2.5`.

Pour l'habillage du SMS, pourrais-je vous demander des impressions d'écran, car c'est une fonctionnalité expérimentale que j'ai commencé à développer à l'aveugle (n'ayant pas de compte free), donc je n'ai pas vraiment idée de ce qui s'affiche sur votre téléphone.

Merci !

**Comment by ObiwanKennedyHep** [comment]
Voici un exemple ! 
(Le "hello World" c'est moi; pas le script).

Si besoin, je peux faire des tests avec vous si vous voulez.

![img_4078](https://cloud.githubusercontent.com/assets/24874744/21589121/cfbac4e0-d0ee-11e6-9ca6-e8d9579ddcb1.PNG)

**Comment by maximelebreton** [comment]
Aaaah, merci !
Pouvez vous passer en `5.2.5` et rééssayer ? (le pb undefined devrait être résolu, et il devrait y'avoir un signe € pour le prix)

Qu'entendez vous par habillage de texte ? Car vu qu'il s'agit d'un SMS, les seules possibilités sont le texte brut.
D'ailleurs, vu qu'il s'agit d'un SMS, l'ajout d'image me semble impossible, sauf si l'API de free mobile autorise l'envoi de MMS, je vais me renseigner.

**Comment by ObiwanKennedyHep** [comment]
Oui en 5.2.5 le problème est résolu ! 
Ce que j'aurai imaginé est quelque chose comme ça : 
Titre : %Titre%
Lieu : %location%
Prix : %price%
URL : %url%

avec donc un texte fixe qui annonce la variable et si possible un retour chariot.

Comme tu le verras sur l'impression écran, il y a un bug avec l'encodage des caractères (apostrophe et &).

![img_4079](https://cloud.githubusercontent.com/assets/24874744/21589997/fd4e1a2a-d0f7-11e6-8e64-53f852fb1bd3.PNG)

**Comment by maximelebreton** [comment]
@ObiwanKennedyHep l'affichage d'une image n'est pas possible pour le moment car il s'agit de SMS, et non de MMS, et concernant les autres problèmes ou suggestions j'ai ouvert des issues spécifiques : 
https://github.com/maximelebreton/alertes-leboncoin/issues/19
https://github.com/maximelebreton/alertes-leboncoin/issues/20

je ferme car l'issue principale est résolue.
