### ISSUE TITLE
Réception de mail en 4 exemplaire

### ISSUE THREAD

**Issue by stchenot** [maximelebreton/alertes-leboncoin#21]
Bonjour maxime,  je tiens déjà à te remercier pour le travail que tu fourni. Cette feuille est vraiment pratique pour ce qui aiment chiner sur lbc. Je me permet d'ouvrir un issue car j'ai un problème. La première fois que j'ai installé la feuille bête la librairie tout fonctionnait bien. J'ai entre temps fait une première mise à jour et depuis je reçois les mail d'alerte en double. J'ai depuis installé la version 2.2.4 puis la 2.5 et je reçois maintenant à chaque fois quatre fois le même mail.
Une idée d'où pourrait venir le problème? 
Par avance merci pour ton aide.

**Comment by maximelebreton** [comment]
Bonjour, pourriez vous vérifier que vous n'avez pas créé plusieurs feuilles de calcul ?
(aussi, il s'agit normalement de la `5.2.4` et `5.2.5`)
Si vous cliquez sur le lien "éditer mes alertes" de chacun des mails (tout en bas) vous devriez vite vous rendre compte s'il s'agit de la même feuille de calcul ou non.

**Comment by maximelebreton** [comment]
ok, je pense que vous avez supprimé les feuilles de calcul mais pas les déclencheurs.
Donc je vous suggère de retrouver les feuilles de calcul qui sont dans votre corbeille, puis d'aller pour chacune de ces feuilles dans `Outils > Editeurs de script > Ressources > Déclencheurs du projet actuel` et que vous supprimiez le déclencheur.
Concernant le lien "editer mes alertes", j'indiquais qu'il se trouvait en bas des **mails** que vous recevez.

**Comment by maximelebreton** [comment]
Si vous avez créé une nouvelle feuille de calcul à chaque mise à jour, sachez que ce n'est pas nécessaire, il suffit d'aller dans `Outils > Editeurs de script > Ressources > Bibliothèques` comme décrit dans la procédure suivante : 
https://github.com/maximelebreton/alertes-leboncoin#obtenir-la-dernière-mise-à-jour
