### ISSUE TITLE
Echec du script

### ISSUE THREAD

**Issue by bigblueboy** [maximelebreton/alertes-leboncoin#22]
Bonjour Maxime,
Tout d'abord merci pour votre travail remarquable.
J'ai un petit problème mineur, tout les jours j'ai un "Résumé des échecs de Google Apps Script"
![capture](https://cloud.githubusercontent.com/assets/26040182/23339691/e838e8d0-fc27-11e6-886f-0147b47b3dbb.PNG)
L'url initial dans la feuille est : https://www.leboncoin.fr/vetements/offres/ile_de_france/?th=1&q=six%20sept&parrot=0&ct=3
La seul différence est le "amp;" après chaque "&", je ne sais pas si c'est normal
Sinon le problème survient chaque jour mais pas forcément pour la même recherche

Merci d'avance et bon dimanche
Samuel

**Comment by maximelebreton** [comment]
Effectivement j'ai noté ça chez moi aussi, et de manière aléatoire...
A priori cela viendrait du site leboncoin.fr, mais la question est pourquoi...
Avez vous beaucoup de recherches, et à quelle fréquence avez vous réglé les envois ?

**Comment by bigblueboy** [comment]
________________________________
De : Maxime Le Breton <notifications@github.com>
Envoyé : lundi 27 février 2017 12:05:02
À : maximelebreton/alertes-leboncoin
Cc : bigblueboy; Author
Objet : Re: [maximelebreton/alertes-leboncoin] Echec du script (#22)


Effectivement j'ai noté ça chez moi aussi, et de manière aléatoire...
A priori cela viendrait du site leboncoin.fr, mais la question est pourquoi...
Avez vous beaucoup de recherches, et à quelle fréquence avez vous réglé les envois ?

**Comment by bigblueboy** [comment]
Bonjour Maxime,
Je m'y connais pas du tout en codage
Alors le problème est arrive samedi et dimanche dernier (avant aucun soucis) peut être va t il se résoudre de lui même
J ai deux feuilles avec 50 recherches chacunes à peu près et le déclencheur est réglé tout les 4h
Après j ai pas beaucoup de recul mais le problème semble aléatoire et ne touche qu'une ou deux recherches par feuille et par jour
________________________________
De : Maxime Le Breton <notifications@github.com>
Envoyé : lundi 27 février 2017 12:05:02
À : maximelebreton/alertes-leboncoin
Cc : bigblueboy; Author
Objet : Re: [maximelebreton/alertes-leboncoin] Echec du script (#22)


Effectivement j'ai noté ça chez moi aussi, et de manière aléatoire...
A priori cela viendrait du site leboncoin.fr, mais la question est pourquoi...
Avez vous beaucoup de recherches, et à quelle fréquence avez vous réglé les envois ?

**Comment by maximelebreton** [comment]
Ok.
Alors je viens de mettre en place en `5.2.6` une fonction qui permets d'attendre une seconde puis de relancer 2 tentatives d'appel de l'url lorsqu'une `erreur 500` est rencontrée, donc cela devrait résoudre le problème (si bien sur l'erreur est simplement ponctuelle).

Aussi, j'ai muté par défaut les exceptions http envoyées par Google App Script, pour ne pas perturber les utilisateurs qui ne vont pas comprendre ces messages d'erreur.
Mais si vous tenez à conserver ces messages, il suffit d'indiquer le paramètre global `muteHttpExceptions` sur `false`.

**Comment by bigblueboy** [comment]
Merci beaucoup pour tout ce boulot
Je met à jour dès que je rentre chez moi
Bonne fin de journée
________________________________
De : Maxime Le Breton <notifications@github.com>
Envoyé : lundi 27 février 2017 13:21:18
À : maximelebreton/alertes-leboncoin
Cc : bigblueboy; Author
Objet : Re: [maximelebreton/alertes-leboncoin] Echec du script (#22)


Ok.
Alors je viens de mettre en place en 5.2.6 une fonction qui permets d'attendre une seconde puis de relancer 2 tentatives d'appel de l'url lorsqu'une erreur 500 est rencontrée, donc cela devrait résoudre le problème (si bien sur l'erreur est simplement ponctuelle).

Aussi, j'ai muté par défaut les exceptions http envoyées par Google App Script, pour ne pas perturber les utilisateurs qui ne vont pas comprendre ces messages d'erreur.
Mais si vous tenez à conserver ces messages, il suffit d'indiquer le paramètre global muteHttpExceptions sur false.
