### ISSUE TITLE
TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")	

### ISSUE THREAD

**Issue by Ovape** [maximelebreton/alertes-leboncoin#23]
Alors, je reçois ça par mail, aléatoirement !

"________________________________
L'exécution de votre script, [template] Alertes LeBonCoin 5.2.6, a récemment échoué. Un résumé des échecs est fourni ci-dessous. Pour configurer les déclencheurs pour ce script ou modifier vos paramètres pour recevoir les futures notifications d'échec, cliquez ici.

Le script est utilisé par le document Copie de [template] Alertes LeBonCoin 5.2.6.

Résumé :
Message d'erreur	Nombre d'exécutions
TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")	3

Début	Fonction	Message d'erreur	Déclencheur	Fin
19/03/17 18:26	alertesLeBonCoin	TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")	time-based	19/03/17 18:27
19/03/17 20:26	alertesLeBonCoin	TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")	time-based	19/03/17 20:28
20/03/17 00:26	alertesLeBonCoin	TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")	time-based	20/03/17 00:27

Cordialement,

Google Apps Script
______________________________________
"

**Comment by maximelebreton** [comment]
Si cela ne vous pose pas de problèmes, pourrais-je avoir la liste de vos urls de recherche ?
Car de mon côté je n'arrive pas à reproduire pour le moment.

**Comment by Ovape** [comment]
Hello, j’ai 2 fiches car je ne pouvais pas tout mettre sur 1 seule, ça n’envoyait plus de mail!

Lien
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20Juno%20106&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20Juno-106&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Korg%20SDD-1000&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Korg%20SDD%201000&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Korg%20SDD%201200&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Korg%20SDD-1200&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Korg%20SDD-3000&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Korg%20SDD%203000&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20Juno%206&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20Juno-6&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=expandeur&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=synth%E9tiseur%20rack&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=roland%20r8m&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=roland%20r-8m&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?o=1&q=module
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=boite%20%E0%20rythmes&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Yamaha%20DX7&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Yamaha%20DX-7&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Yamaha%20DX%207&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Synth%E9%20vintage&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Synth%E9tiseur%20vintage&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=clavier%20vintage&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=lot%20machine&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=lot%20mat%E9riel&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=ensemble%20mat%E9riel&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20JD800&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20JD-800&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20JD%20800&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20jx3p&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20jx-3p&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20jx-8p&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20jx8p&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20pg&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20MKS&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20MKS-50&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20MKS-70&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20MKS%2070&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=synth%E9%20expandeur&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=synth%E9tiseur%20expandeur&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=clavier%20expandeur&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=piano%20expandeur&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=expandeur%20vintage&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Synth%E9tiseur%20module&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Synth%E9%20module&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=rack%20effet&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=synth%E9%20rack&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=clavier%20rack&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=piano%20rack&parrot=0




Lien
https://www.leboncoin.fr/annonces/offres/poitou_charentes/bonnes_affaires/?th=1&q=synth%E9tiseur%20&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/bonnes_affaires/?th=1&q=synth%E9&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=synth%E9tiseur%20analogique&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Ensoniq&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=E-mu&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20Juno%2060&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20Juno-60&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Sequencial%20Circuit&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=elka%20&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=boss%20dr%20770&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=akai%20mpc%202500&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=akai%20mpc%204000&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Akai%20MPC%202000&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Akai%20MPC%202000%20XL&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Akai%20MPC%202000XL&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Akai%20MPC%201000&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=Home%20studio&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=Homestudio&parrot=0
https://www.leboncoin.fr/image_son/offres/poitou_charentes/occasions/?th=1&q=homestudio&parrot=0
https://www.leboncoin.fr/image_son/offres/poitou_charentes/occasions/?th=1&q=home%20studio&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=synth%E9tiseur%20roland&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=synth%E9tiseur%20korg&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=sampleur&parrot=0
https://www.leboncoin.fr/image_son/offres/poitou_charentes/occasions/?th=1&q=sampler&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=sampler&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Casio%20rz-1&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20S-760&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20S760&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Xoxbox%20Ladyada&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Sony%20DPS%20V77&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Sony%20DPS%20V-77&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Ensoniq%20DP4&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Ensoniq%20DP-4&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Nakamichi%20MR-1&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Roland%20PG-800&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=emu&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=clavier%20analogique&parrot=0
https://www.leboncoin.fr/instruments_de_musique/offres/poitou_charentes/occasions/?th=1&q=clavier%20synth%E9tiseur&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Blackberry%20passport&parrot=0
https://www.leboncoin.fr/annonces/offres/poitou_charentes/occasions/?th=1&q=Blackberry%20passeport&parrot=0





Le 20 mars 2017 à 20:41, Maxime Le Breton <notifications@github.com<mailto:notifications@github.com>> a écrit :


Si cela ne vous pose pas de problèmes, pourrais-je avoir la liste de vos urls de recherche ?
Car de mon côté je n'arrive pas à reproduire pour le moment.

**Comment by Ovape** [comment]
Hello, de nouveaux messages d’erreurs cette nuit..


Résumé :

Message d'erreur        Nombre d'exécutions
L'utilisation du service sur une journée a pris trop de temps.  2
TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")      3


Début   Fonction        Message d'erreur        Déclencheur     Fin
20/03/17 02:32  alertesLeBonCoin        TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")      time-based      20/03/17 02:33
20/03/17 06:32  alertesLeBonCoin        TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")      time-based      20/03/17 06:33
20/03/17 10:32  alertesLeBonCoin        L'utilisation du service sur une journée a pris trop de temps.  time-based      20/03/17 10:32
20/03/17 12:32  alertesLeBonCoin        L'utilisation du service sur une journée a pris trop de temps.  time-based      20/03/17 12:32
20/03/17 16:32  alertesLeBonCoin        TypeError: Impossible d'appeler la méthode "indexOf" de undefined. (ligne 29, fichier "utils", projet "alertes_leboncoin")      time-based      20/03/17 16:33

Le 20 mars 2017 à 20:41, Maxime Le Breton <notifications@github.com<mailto:notifications@github.com>> a écrit :


Si cela ne vous pose pas de problèmes, pourrais-je avoir la liste de vos urls de recherche ?
Car de mon côté je n'arrive pas à reproduire pour le moment.

**Comment by Ovape** [comment]
Hello,

Alors, une idée :) ?

Alex


Le 20 mars 2017 à 20:41, Maxime Le Breton <notifications@github.com<mailto:notifications@github.com>> a écrit :


Si cela ne vous pose pas de problèmes, pourrais-je avoir la liste de vos urls de recherche ?
Car de mon côté je n'arrive pas à reproduire pour le moment.

**Comment by maximelebreton** [comment]
Oui.
Si ce n'est pas indiscret, quel usage faites vous de ce script ?
Car vu vos recherches, vous devez recevoir plusieurs centaines d'annonces par jour ?
Cela me semble beaucoup pour l'usage raisonnable recommandé, et vous êtes donc confrontés aux limitations du service : https://github.com/maximelebreton/alertes-leboncoin#limitations

Deux solutions :
- Affiner ses recherches et éviter les doublons
- Ou aller vers une solution payante

**Comment by Ovape** [comment]
Ok!

Je collectionne des synthétiseurs, boites à rythmes, samplers.. vintage, et ça part super vite!

Ok bon, merci quand même ! ;)


Le 26 mars 2017 à 16:21, Maxime Le Breton <notifications@github.com<mailto:notifications@github.com>> a écrit :


Oui.
Si ce n'est pas indiscret, quel usage faites vous de ce script ?
Car vu vos recherches, vous devez recevoir plusieurs centaines d'annonces par jour ?
Cela me semble beaucoup pour l'usage raisonnable recommandé, et vous êtes donc confrontés aux limitations du service : https://github.com/maximelebreton/alertes-leboncoin#limitations

Deux solutions :

  *   Affiner ses recherches et éviter les doublons
  *   Ou aller vers une solution payante

**Comment by Ovape** [comment]
Ok, intéressantes les limitations, je ne pensais pas que leboncoin pouvait le remarquer!

Le 26 mars 2017 à 16:21, Maxime Le Breton <notifications@github.com<mailto:notifications@github.com>> a écrit :


Oui.
Si ce n'est pas indiscret, quel usage faites vous de ce script ?
Car vu vos recherches, vous devez recevoir plusieurs centaines d'annonces par jour ?
Cela me semble beaucoup pour l'usage raisonnable recommandé, et vous êtes donc confrontés aux limitations du service : https://github.com/maximelebreton/alertes-leboncoin#limitations

Deux solutions :

  *   Affiner ses recherches et éviter les doublons
  *   Ou aller vers une solution payante
