### ISSUE TITLE
Boite de dialogue trop petite pour afficher les boutons

### ISSUE THREAD

**Issue by raemin** [maximelebreton/alertes-leboncoin#24]
Lors de l'appel "planifier l'envoi des alertes", Google rajoute un message d'alerte qui modifie la disposition au sein de la boite de dialogue, ce qui a pour effet de rendre les boutons inaccessibles.

![2017-03-21](https://cloud.githubusercontent.com/assets/16685636/24150834/35a03782-0e47-11e7-97b1-fa62d8b8d9ec.png)

**Comment by maximelebreton** [comment]
Bonjour, je n'arrive pas à obtenir ce petit message encadré de gris (pourtant j'ai essayé avec plusieurs comptes différents), mais cela sera corrigé dans la prochaine version.
Merci pour la remontée !

**Comment by maximelebreton** [comment]
Cela a été pris en compte dans la `5.3.0`. Merci !
