### ISSUE TITLE
Erreur envoie de mail paramètre avancée

### ISSUE THREAD

**Issue by Pascal-m** [maximelebreton/alertes-leboncoin#25]
Bonjour,
J'ai une erreur quand je veux rediriger une annonce vers un mail en particulier .Dans la colonne Paramètres avancées j'ai rentré l'option comme ceci:

{"email":"monmail2@gmail.com"}

Je suis en version 5.2.7
Merci

**Comment by maximelebreton** [comment]
j'ai identifié le problème, ce sera résolu dans la prochaine version. 
je vous tiens au courant dès qu'elle sort.

**Comment by matthieugoua** [comment]
je rencontre le même souci j'ai essayé de le régler mais sans succès

**Comment by maximelebreton** [comment]
Cela sera corrigé dans la prochaine version qui arrive très prochainement avec de nouvelles fonctionnalités.

**Comment by maximelebreton** [comment]
@Pascal-m, @matthieugoua, comme je tarde à sortir la nouvelle version, j'ai mis en place un correctif dans la `5.3.0` qui règle ce problème.
