### ISSUE TITLE
Avertissement message dangereux sur Gmail

### ISSUE THREAD

**Issue by erics102** [maximelebreton/alertes-leboncoin#26]
Bonjour,
Depuis 1 ou 2 jours, gmail indique la possibilité que le message soit d'origine frauduleuse.
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="https://img15.hostingpics.net/pics/97473620171012084406.jpg" border="0" alt="Hebergeur d'image" /></a>
Peut être que ça vient de gmail...
Merci.

**Comment by reppad** [comment]
Bonjour,
Même comportement chez moi depuis quelques jours.

**Comment by pdewas** [comment]
Même chose de mon côté sur Inbox sur PC.

**Comment by erics102** [comment]
Le problème semble être réglé, cela ne se produit plus.

**Comment by reppad** [comment]
Aucun blocage de message depuis plusieurs mois, semble réglé pour moi aussi.

**Comment by maximelebreton** [comment]
étrange, pas vu passer chez moi... je clos
