### ISSUE TITLE
Garder la liste des annonces pour suivre aussi leur disparition

### ISSUE THREAD

**Issue by KafetzisT** [maximelebreton/alertes-leboncoin#27]
Bonjour,

Je me demandais s'il est aussi possible de copier les résultats dans un nouveau spreadsheet.
Puis à la prochaine exécution de faire une mise à jour de ces résultats.

Mon but est simplement pour une annonce, de voir combien de temps elle a passé en ligne avant de disparaître.

Il y a un ID qui permettrait d'identifier les annonces pour cela ?

**Comment by maximelebreton** [comment]
Bonjour, voyant là un usage spécifique, je n'ai pas prévu d'implémenter cela.
Les solutions payantes le proposent peut être ?
