### ISSUE TITLE
plus d'alertes depuis le 26/04/18

### ISSUE THREAD

**Issue by squalatak** [maximelebreton/alertes-leboncoin#29]
plus rien depuis aujourdhui .
j'ai verifier mais je ne trouve pas le probleme

help

ps: j'utilise alertes leboncoin depuis 1 an !!!

**Comment by maximelebreton** [comment]
désolé, mais sans détails, je ne peux pas vous aider, je clos donc.
(pour information il y'a une nouvelle version `5.4.3`)
