### ISSUE TITLE
ReferenceError: L'élément "email" n'est pas défini

### ISSUE THREAD

**Issue by vjaunet** [maximelebreton/alertes-leboncoin#30]
Bonjour,
Je viens d'avoir un petit souci en changeant l'adresse mail sur une recherche.
Il semblerait qu'il y ait un souci sur l'objet JSON car en mettant {"email":"test@mail.com"} comme spécifé dans l'aide, j'obtiens un erreur : ReferenceError: L'élément "email" n'est pas défini
++,
V

**Comment by maximelebreton** [comment]
Bonjour, je n'arrive pas à reproduire votre erreur, pourriez vous me faire un screenshot de votre spreadsheet (en floutant ce qui est indiscret bien sur)?

**Comment by vjaunet** [comment]
Bonjour,
Je crois que le problème vient du fait que l'option groupedResults était à l'état TRUE et que je seulement une de mes deux requêtes avait un email différent du mail par défaut. 
Cela semble marcher avec groupedResults = FALSE, ce qui a du sens.
Merci beaucoup.
