### ISSUE TITLE
Pas de photo

### ISSUE THREAD

**Issue by bcastaing** [maximelebreton/alertes-leboncoin#34]
Bonjour, j'utilise le fichier 5.4.1 avec mise à jour bibliothèque en 5.4.2 et les photos n'apparaissent pas dans les mails. Comment puis je solutionner ? merci et BRAVO pour votre EXCELLENT travail !!

**Comment by maximelebreton** [comment]
Et oui, c'est totalement dépendant de ma volonté, leboncoin a récemment effectué des changements, cf:
https://github.com/maximelebreton/alertes-leboncoin/issues/33#issuecomment-394269696

Je leur ai signalé la négligence via [twitter](https://twitter.com/maximelebreton/status/1003605430029946880), mais ils n'ont même pas pris la peine de me répondre.

Pour avoir plus de poids, n'hésitez pas à [retweeter ce message](https://twitter.com/maximelebreton/status/1003605430029946880) ou passer par d'autres moyens de signalement, mais attention à ne pas mentionner `Alertes LeBonCoin`, car ils n'approuvent pas ce système
---

**Comment by bcastaing** [comment]
Merci pour ce retour. Effectivement j'ai vu le post précédent aprés coup.
En tous les cas BRAVO pour le travail effectué. Je m'en sert encore
beaucoup, mais sans les photos désormais.

Très bonne journée

Cordialement
Bruno CASTAING


Le mer. 13 juin 2018 à 11:54, Maxime Le Breton <notifications@github.com> a
écrit :

**Comment by jfallot** [comment]
J'ai trouvé une solution pour le problème avec les images, cf mon fork sous https://github.com/jfallot/alertes-leboncoin
Pour @maximelebreton, tu verras dans les commits qu'il y a maintenant une structure JSON en fin des réponses HTML aux recherches par catégorie.

Sinon si quelqu'un a des infos sur l'API sous https://api.leboncoin.fr/, je suis preneur :)

**Comment by bcastaing** [comment]
BRAVO !! trop fort !!
Respect à tous pour le travail que vous faites !!

**Comment by maximelebreton** [comment]
hello @jfallot !
j'avais commencé à creuser le `window.FLUX_STATE` également (que je trouvais trop beau pour être vrai),
mais j'avais stoppé assez vite car le code était coupé lorsque j'inspectais le markup via les Chrome devtools:

![image](https://user-images.githubusercontent.com/1072425/41457195-2a72f652-7083-11e8-96cf-2a0194c1792b.png)

(là ça s'arrête au bout de la 4e annonce par exemple)

Mais comme tu me dis que ça a marché chez toi, je viens de tester de récupérer le markup via le `fetchUrl` de Google App Script, et cette fois j'ai bien tout !!!! 

Donc la j’avoue que ça m'échappe complètement ??!
Pourquoi, le markup de `window.FLUX_STATE` serait coupé sur Chrome et pas via le `fetchUrl` App Script... ?
Mystère.

Aussi, je trouve étonnant que leboncoin expose son flux state dans le markup HTML (c'est pas très logique vu que tout est géré en JS), et j'espère que c'est pas une erreur car c'est juste du pain béni pour nous ! 

Bref, superbe nouvelle, en espérant qu'elle soit pérenne :)

Merci en tout cas @jfallot de m'avoir relancé la dessus, je vais mettre en place un correctif prochainement.

(et concernant https://api.leboncoin.fr/, je guette aussi, mais pas d'infos pour l'instant)
