### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Favern** [maximelebreton/alertes-leboncoin#36]
Bonjour,
Avec la version 5.4.3, j'ai cette erreur lorsque je lance le script manuellement : 
"TypeError: Impossible de lire la propriété "0" depuis undefined.DétailsIgnorer".
Cette erreur n'est pas présente en 5.4.2.
Merci pour ton travail
Cordialement
Philippe

**Comment by maximelebreton** [comment]
mmm, étrange, pouvez vous remettre la 5.4.3, et retester, je viens de faire une modif

**Comment by maximelebreton** [comment]
je viens de faire une correction `5.4.4`, est-ce toujours le cas ?

**Comment by Favern** [comment]
C'est ok pour moi sur la 5.4.4.
Merci pour ta réactivité.
