### ISSUE TITLE
[Résolu] Erreur lorsqu'il n'y a pas de résultat

### ISSUE THREAD

**Issue by bm7272** [maximelebreton/alertes-leboncoin#37]
Bonjour,

J'ai actualisé la page et le script, mais je rencontre une erreur lorsque la recherche retourne aucun résultat:
"TypeError: Impossible d'appeler la méthode "map" de undefined."
Exemple: https://www.leboncoin.fr/recherche/?text=Programme%20Hippocrate&category=27

Suis-je le seul? merci pour cet outil !

bm

**Comment by nicohery** [comment]
Je rencontre aussi le problème. Je le rencontre à la 25ème ligne de ma feuille de calcul.
Rien ne permet d'identifier un format d'url différent des recherches qui fonctionnent.

**Comment by maximelebreton** [comment]
Merci pour les précisions (l'url de la recherche et le rapport d'erreur), ça m'a permis de trouver direct le problème. Cela concernait les annonces sans résultat. C'est corrigé dans la `5.4.6`

**Comment by bm7272** [comment]
merci, cela fonctionne :)
Bonne continuation !

**Comment by nicohery** [comment]
Je confirme que ça fonctionne.
Merci !
