### ISSUE TITLE
Envoie auto HS

### ISSUE THREAD

**Issue by con6767** [maximelebreton/alertes-leboncoin#40]
Bonjour, 

Fervent utilisateur, l'automatisation du script ne fonctionne pas depuis 3 jours.

J'ai déjà tout refait

Mise à jour
Réinstallation du script

une idée ?

**Comment by maximelebreton** [comment]
Bonjour,

Pour la réinstallation, vous êtes repartis d'une nouvelle feuille ?
https://goo.gl/Awjw5f

Et vous avez bien suivi les étapes, notamment la n°3 ?
https://github.com/maximelebreton/alertes-leboncoin#pour-commencer

**Comment by con6767** [comment]
AH ben merci Maxime, il me manqué l'étape N°3

**Comment by alexsonnay** [comment]
J'ai bien suivi les étapes, mais cela ne fonctionne pas de mon côté. Le script s'exécute manuellement mais ne met pas à jour la dernière annonce ni n'envoie d'emails.

**Comment by maximelebreton** [comment]
> AH ben... ...il me manqué l'étape N°3

A l'avenir, prenez la peine de lire la documentation (en l’occurrence, les 3 premières lignes...), si les développeurs passent du temps à l'écrire, c'est justement pour ne pas le perdre à expliquer le b.a.-ba.
Le temps passé sur de "faux problèmes" individuels, est du temps qu'on ne passe pas sur de "vrais problèmes" qui pourraient profiter à la communauté.

Merci.
