### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by paclep** [maximelebreton/alertes-leboncoin#41]
Bonjour.

Depuis une dizaine de jours, je ne reçois plus aucun mail d'alerte. Je prends enfin le temps de regarder ce qui peut bloquer. Je suis passé à la dernière version de la feuille (5.5.2), mis à jour le script (65). 
Quand je lance manuellement le script, celui-ci balai bien chaque ligne de ma feuille, mais n'ajoute aucune date dans la colonne "Dernière annonce".

Une idée ? Rien vu sur GitHub ni dans les commentaires ci-dessous qui ressemble à mon soucis.

Désolé pour le doublon avec les commentaires du site officiel, c'était probablement mieux placé ici.

Bonne journée.

**Comment by maximelebreton** [comment]
doublon : https://github.com/maximelebreton/alertes-leboncoin/issues/39
