### ISSUE TITLE
MAXIME HS AUSSI ?

### ISSUE THREAD

**Issue by con6767** [maximelebreton/alertes-leboncoin#43]
Ton superbe script que j'utilise depuissi longtemps, ne marche plus,

nous sommes plusieurs à le dire mais sans réponse de ta part.

Qu'en est il ?

**Comment by erics102** [comment]
Il est peut-être tout simplement occupé ailleurs ou en vacances, il faut lui laisser le temps d'en prendre connaissance et de voir s'il peut faire quelque chose pour ça. Il propose son aide sans rétribution et je le remercie pour ça, mais il n'a aucune obligation envers les utilisateurs du script. Il nous a d'ailleurs mis en garde que les dernière mises à jour duboncoin risquaient de bloquer l'utilisation de robot de recherche... Vu ce qu'il a fait jusqu'à maintenant et la rapidité de ses réponses ou des correctifs, je pense simplement qu'actuellement il ne peut pas faire autrement. Il faut être patient et utiliser la bonne vieille méthode de recherche manuelle ;-)

**Comment by maximelebreton** [comment]
Merci @erics102.

je ferme car doublon avec : https://github.com/maximelebreton/alertes-leboncoin/issues/39
