### ISSUE TITLE
Implémenter l'envoi de SMS ?

### ISSUE THREAD

**Issue by maximelebreton** [maximelebreton/alertes-leboncoin#5]
Avant d'implémenter cette fonctionnalité, j'aimerais connaitre vos usages.

Personnellement, avec une trentaine d'alertes en moyenne, je me vois mal recevoir jusqu'à 30 sms par jour, voir toutes les 2 heures selon les réglages.
Il y'a de plus un risque d'être considéré comme spam par le FAI, ce qui n'est pas souhaitable.

Comment voyez vous cette fonctionnalité ?

**Comment by maximelebreton** [comment]
Depuis la 5.1.0, l'envoi de SMS est en expérimentation (seulement avec Free),
s'il y'a des utilisateurs Free intéressés, signalez vous et je vous expliquerais comment activer la fonctionnalité.

**Comment by james40130** [comment]
bonjour, je suis très intéressé pour implémenter l’envoi de SMS via le script de LBC.
Pouvez vous me dire la marche a suivre ?

**Comment by maximelebreton** [comment]
Si vous voulez tester, il faut d'abord avoir activé l'option dans votre compte [Free Mobile](http://www.universfreebox.com/article/26337/Nouveau-Free-Mobile-lance-un-systeme-de-notification-SMS-pour-vos-appareils-connectes). 

Ensuite, dans la colonne [options avancées](https://github.com/maximelebreton/alertes-leboncoin#options-avancées) (cela agit uniquement sur une ligne, et non l'ensemble), il suffit d'ajouter ces paramètres : `{"sendSms":true,"freeUser":"xxxx","freePass":"xxxx"}`

Dans la 5.1.4, il est possible de définir le `freeUser` et le `freePass` dans les paramètres globaux (`userParams`), ce qui permet d'éviter les répétitions, et n'avoir à ajouter que `{"sendSms":true}` dans la colonne.

Si il y'a moins de 3 résultats par recherche, un Sms avec le détail de l'annonce est envoyé.
Sinon, c'est un résumé qui est envoyé.
Le paramètre global `maxSmsSendByResult` permet de modifier cette valeur par défaut.

L'option `sendSms` reste pour l'instant individuelle, pour éviter les avalanches de Sms.

Merci de me faire part de vos retours pour pouvoir terminer la phase expérimentale.

**Comment by james40130** [comment]
merci pour ces infos, je teste et je vous fais une remonte si tout est ok

**Comment by james40130** [comment]
je reviens vers vous car rien ne fonctionne, je pense que la procédure doit être détaillé point par point au niveau des lignes de code.
la partie Free mobile et activé mais ne fonctionne pas . 
Cela s’adresse a des utilisateurs très avancé au niveau du développement.

**Comment by maximelebreton** [comment]
dites moi ou êtes vous bloqué ?

**Comment by maximelebreton** [comment]
@james40130, pour faire simple, une fois que vous avez créé votre clé d'identification via votre espace Free Mobile, l'activation des Sms dans la feuille de calcul se résume à cette image :
![image](https://cloud.githubusercontent.com/assets/1072425/20487912/81262752-b005-11e6-8e2f-52c9e66af837.png)

**Comment by maximelebreton** [comment]
et si vous souhaitez ne définir le `freeUser` et le `freePass` qu'une seule fois, cela peut se faire directement dans l'onglet `paramètres utilisateurs` :   

![image](https://cloud.githubusercontent.com/assets/1072425/20488962/3991746a-b009-11e6-90d5-56a0b1740a9c.png)

ainsi, il n'y a que le paramètre `sendSms` à indiquer :  

![image](https://cloud.githubusercontent.com/assets/1072425/20489060/93916150-b009-11e6-95c2-70d5c7ffbe63.png)

**Comment by james40130** [comment]
juste pour dire merci, ça fonctionne a merveille.
effectivement dans la partie paramètres utilisateurs tout était bon sauf que javais inséré "sendsms" au dessus de "freeuser" au lieu de le placer dans la case paramètres avancés.
merci pour la procédure très détaillé et de qualité.
