### ISSUE TITLE
Modifier la fréquence de rafraichissement par alerte

### ISSUE THREAD

**Issue by bisonfute** [maximelebreton/alertes-leboncoin#8]
Bonjour,
tout d'abord, merci beaucoup pour tout le travail fait. C'est vraiment joli.

Ensuite, je voulais demander s'il y avait un moyen de configurer alerte par alerte la fréquence de refresh des annonces. En effet, des annonces sur un sujet sensible méritent d'être rafraichies toutes les 2 heures tandis que pour d'autres sujets, une rafraichissement tous les jours ou tous les 2 jours est suffisant.

Merci!

**Comment by maximelebreton** [comment]
Bonjour @bisonfute, pour mieux comprendre, pourriez vous me donner un exemple de votre cas d'utilisation et le bénéfice de cette amélioration ?

Merci !

**Comment by bisonfute** [comment]
Bonjour,
par exemple, j'ai 2 recherches de configurées : 
- une recherche de location d'un studio à Paris
- l'achat des 25 tomes de la BD walking dead

Pour le studio, j'ai besoin de recevoir un email tous les 2 heures car la réactivité est extrêmement importante. L'offre est assez forte mais le besoin aussi, tout part très vite.
Pour la bd, la pression est bcp moins importante, donc recevoir un email tous les 2 jours me convient mieux.

J'ai l'impression que je ne peux pas régler "annonce par annonce" le déclencheur mais qu'il est commun à chacune. Donc comment réaliser mon besoin?

Merci et bonne journée,

jn.

**Comment by maximelebreton** [comment]
Je viens de mettre en place une version 5.1.6 ou il vous est possible d'ajouter dans les [paramètres avancés individuels](https://github.com/maximelebreton/alertes-leboncoin#individuels), le paramètre `hourFrequency` qui prends pour valeur un nombre exprimé en heures.

exemple : `{"hourFrequency": 48}`

**important :** ce nombre ne peut pas aller en dessous de celui du déclencheur principal !
(si le déclencheur principal est réglé sur _12 heures_, un `hourFrequency` à `6` n'aura pas d'effet.)

en espérant que cela réponde à vos besoins.

**Comment by bisonfute** [comment]
C'est absolument parfait, merci. pile poil mon besoin.
Bravo et merci.

**Comment by bisonfute** [comment]
juste une question @maximelebreton : est-ce qu'il faut que ce paramètre soit un multiple du déclencheur principal ?
Déclencheur principal sur 24h et hourFrequency individuel positionné à 36h, est-ce que ça va fonctionner?

merci!

**Comment by maximelebreton** [comment]
oui, car l'algo détecte simplement la date de la dernière annonce qui a été envoyée, et fait la différence avec la valeur de `hourFrequency`, donc du moment que la valeur est au dessus du déclencheur principal, ça se fait à l'heure près ;)
(dans votre cas même un `hourFrequency` à `25`h fonctionnerait)

**Comment by bisonfute** [comment]
ok super, merci!
