### ISSUE TITLE
Détection de changement de prix

### ISSUE THREAD

**Issue by Dreaky255** [maximelebreton/alertes-leboncoin#9]
Implémentation d'un changement de prix suite à une re-publication d'une même annonce.
Cette info pourrait simplement être affichée sur les résultats par un "Prix inchangé"; "Ancien prix : XX€" etc...
Cette fonction pourrait être activable via les options avancées (par exemple "display_price_change") pour ne pas perturber les utilisateurs qui n'en n'ont pas besoin.

La détection pourrait être basée sur la création d'une clef créée sur les données (titre de l'annonce; numéro de tel). Et pourquoi pas un algo de reconnaissance de texte, avec un pourcentage de similarité à définir. Si la nouvelle annonce match avec une précédente (sans ambiguïté possible), afficher alors l'info de changement de prix.

Je ne sais pas si c'est techniquement possible. C'est juste une idée.
A clôturer si trop complexe/impossible.

**Comment by maximelebreton** [comment]
Je vais réfléchir à la question,
mais cela demanderait de stocker toutes les annonces avec leur prix pour pouvoir les comparer derrière, ce qui viendrait largement compliquer la feuille de calcul.
Je suis en train de tester la modification de prix d'une annonce pour voir si je ne peux pas récupérer cette variable directement via le site leboncoin.fr
Mais vu ce qu'ils mettent à disposition dans leur code source, cela m'étonnerait...

à suivre !

**Comment by Dreaky255** [comment]
Peut-être que cela pourrait être activable uniquement sur certaines catégories d'annonces, comme par exemple les annonces de véhicules ou de biens immobiliers. 
Je verrai pas trop l'intérêt de l'implémenter pour des fringues, ou autres, pour lesquelles le nombre d'annonces explose et où elles sont rarement republiées avec baisse de prix.

**Comment by maximelebreton** [comment]
Après quelques recherches, je n'ai pas trouvé le moyen de récupérer les informations nécessaires à l'élaboration de cette fonctionnalité à partir du site.

Votre idée est intéressante mais trop complexe à mettre en place si je dois passer par des algorithmes de détection et un stockage massif de données.

Je clôture donc pour l'instant, mais n'hésiterai pas à rouvrir s'il y'a du changement !
